# Generated by Django 6.0.3 on 2026-03-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='jobs_img/%y%m%d'),
        ),
    ]
